name: Publish Latest Artifacts

on:
  schedule:
    - cron: "25 2 * * 1"
  workflow_dispatch:

jobs:
  determine-versions:
    name: Determine versions to publish
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}

    steps:
      - uses: AshsWorkshop/actions/checkout@4b6fee62c3383c7c4a8b7878a74cce7707a98421 # main
        with:
          ref: ${{ github.ref_name }}

      - name: Get versions
        id: get_versions
        shell: bash
        run: |
          # Output list
          echo "versions=$(jq -c '.latest' releases.json)" >> $GITHUB_OUTPUT

  publish:
    needs:
      - determine-versions
    uses: ./.github/workflows/publish.yml
    with:
      versions: ${{ needs.determine-versions.outputs.versions }}
      UUID_USERNAME: ${{ vars.UUID_USERNAME }}
    secrets: inherit

    permissions:
      contents: write
      packages: write
